## TrilioVault Operator
registry: gcr.io/amazing-chalice-243510

operator-webhook-init:
  repository: operator-webhook-init

k8s-triliovault-operator:
  repository: k8s-triliovault-operator

tag: master

image:
  pullPolicy: Always
tls:
  secretName: "helm-client-certs"
  verify: false
  enable: false
  keyFile: "tls.key"
  certFile: "tls.crt"
  caContent: ""
  hostname: ""

nameOverride: ""
