apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "k8s-triliovault-operator.name" . }}-validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "k8s-triliovault-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-triliovault-trilio-io-v1-triliovaultmanager
  failurePolicy: Fail
  name: vtriliovaultmanager.kb.io
  rules:
  - apiGroups:
    - triliovault.trilio.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - triliovaultmanagers
